# -*- coding: utf-8 -*-
"""system_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeDvs5YB3ADxzIATGy7Qtmm0Yyc2p3hI
"""

from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')

print("Please confirm that 'skills_dataset.xlsx' is among the uploaded files.")

import pandas as pd

# Load knowledge base
df = pd.read_excel('skills_dataset.xlsx')

# Enhanced cleaning
df['Skill'] = df['Skill'].astype(str).str.replace('\xa0', ' ', regex=False)
df['Skill'] = df['Skill'].str.replace(r'\s+', ' ', regex=True)  # Replace multiple spaces with single space
df['Skill'] = df['Skill'].str.strip().str.lower()

# Debug: Print all skills to see what's actually in your data
print("Available skills in dataset:")
print(df['Skill'].head(20))  # Print first 20 skills
print(f"\nTotal skills: {len(df)}")

# Create dictionary
knowledge_base = dict(zip(df['Skill'], df['Recommended Careers']))

# Get user input with enhanced cleaning
skill = input('Enter your skill: ').strip().lower()
skill = ' '.join(skill.split())  # Normalize whitespace

print(f"Searching for: '{skill}'")

# Lookup with fuzzy matching fallback
if skill in knowledge_base:
    careers = knowledge_base[skill].split(', ')
    print(f'\nBased on your skill in {skill.title()}:')
    print('✔ Recommended Careers:')
    for c in careers:
        print(f' - {c}')
else:
    # Try partial matching
    matches = [k for k in knowledge_base.keys() if skill in k or k in skill]
    if matches:
        print(f"\nClose matches found: {matches}")
        print(f"Did you mean: {matches[0]}?")
        careers = knowledge_base[matches[0]].split(', ')
        print('✔ Recommended Careers:')
        for c in careers:
            print(f' - {c}')
    else:
        print('Sorry, no recommendations found for this skill.')

# Commented out IPython magic to ensure Python compatibility.
# Step 1: Configure Git (run these commands in Colab)
!git config --global user.name "vanessaNjoroge2"
!git config --global user.email "your-email@example.com"

# Step 2: Clone your repository
!git clone https://github.com/vanessaNjoroge2/AI_Practical-Assignment.git

# Step 3: Navigate to the repository
# %cd AI_Practical-Assignment

# Step 4: Copy your files to the repository
# For example, if you have a Python file:
!cp /content/your_script.py ./

# Or if you're working in the current directory:
!cp *.py ./
!cp *.ipynb ./
!cp *.txt ./
!cp *.csv ./

# Step 5: Add files to git
!git add .

# Step 6: Commit changes
!git commit -m "Add AI practical assignment code from Colab"

# Step 7: Push to GitHub
!git push